version: '2.34'

services:
  postgresdb:
    image: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  docker-demo:
    build: ./
    ports:
      - '3001:3000'
    depends_on:
      - postgresdb

volumes:
  pgdata: